name: Python push on main branch

on:
  push:
    branches: [main]

env:
  DOCKER_USERNAME: davydehaas98
  DOCKER_REGISTRY: ghcr.io
  DOCKER_IMAGE: davydehaas98/homelab
  DOCKER_TAG: main-${{ github.sha }}
  TARGET_DIRECTORY: ./docker-compose/homelab

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - uses: docker/setup-qemu-action@v1

    - uses: docker/setup-buildx-action@v1
    
    - name: Publish Docker image
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ${{ env.DOCKER_REGISTRY }} -u ${{ env.DOCKER_USERNAME }} --password-stdin
        docker buildx build -t ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }} --platform=linux/amd64,linux/arm64,linux/arm/v7 .
        docker push ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
